import Head from 'next/head';
import { dehydrate, QueryClient } from '@tanstack/react-query';
import { fetchHotels } from '@/hooks/useHotels';
import HotelInfiteScroll from '@/components/partials/Hotels/HotelInfiteScroll';
import Scaffold from '@/components/widgets/Scaffold';

const Home = () => {
  return (
    <>
      <Head>
        <title>Hotels&Co - Best hotels at affordable price</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Scaffold>
        <HotelInfiteScroll />
      </Scaffold>
    </>
  );
};

export async function getStaticProps() {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery(['hotels'], fetchHotels);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
    revalidate: 10,
  };
}

export default Home;

